# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ruban Writes
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  I focus on writing about public cloud computing, distributed computing, and other tech-related subjects. Lately, my curiosity has been drawn to New GenAI, and I'll be sharing my insights on this exciting topic soon. Stay tuned!
baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://127.0.0.1:4000" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://me.rubz.xyz"
twitter_username: suseendran
github_username:  neelaruban

# Build settings
# theme: minima
remote_theme: jekyll/minima
minima:
  skin: auto
  social_links:
    - { platform: github ,user_url: https://github.com/neelaruban }
    - { platform: twitter ,user_url: https://twitter.com/suseendran }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/suseendran" }
    - { platform: instagram,      user_url: "https://www.instagram.com/suseendran" }
plugins:
  - jekyll-feed
  - jekyll-feed
  - jekyll-remote-theme


google_analytics: G-Q0X9FZXBYS
show_excerpts: true


twitter:
  username: suseendran
  card: summary

author:
  twitter: suseendran

social:
  name: Ruban Suthan
  links:
    - https://twitter.com/suseendran
    - https://www.facebook.com/
    - https://www.linkedin.com/in/\
    - https://github.com/benbalter
    - https://keybase.io/benbalter

permalink: /:categories/:title/
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
