domain: rubz.xyz       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://me.rubz.xyz  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /ruban-site/      # place folder name if the site is served in a subfolder